{
 "title": "System",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"below-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_stats\")\n  |> filter(fn: (r) => r[\"Hostname\"] == \"raspi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Usage\")"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"below-bucket\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"system_stats\")\n  |> filter(fn: (r) => r._field == \"Total\" or r._field == \"Available\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with mem_percent: 100.0 * (1.0 - float(v: r.Available)/float(v: r.Total)) }))\n  |> keep(columns: [\"_time\", \"mem_percent\"])"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"below-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system_stats\")\n  |> filter(fn: (r) => r[\"Hostname\"] == \"raspi\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Boot_Time_Epoch\")\n  |> map(fn: (r) => ({\n    r with uptime_days: int(v: r._time) / 1000000000 - r._value\n  }))\n  |> keep(columns: [\"_time\", \"uptime_days\"])"
    }
   ]
  },
  {
   "title": "CUP Usage (System & User)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"below-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system_stats\")\n  |> filter(fn: (r) => r._field == \"User\" or r._field == \"System\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"Hostname\", \"_start\", \"_stop\"])\n"
    }
   ]
  },
  {
   "title": "Eth0 RX Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"below-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iface_stats\")\n  |> filter(fn: (r) => r[\"Interface\"] == \"eth0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RX_Bytes\")"
    }
   ]
  },
  {
   "title": "Eth0 Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"below-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iface_stats\")\n  |> filter(fn: (r) => r[\"Interface\"] == \"eth0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"RX_Bytes_s\" or r[\"_field\"] == \"TX_Bytes_s\")\n"
    }
   ]
  },
  {
   "title": "Mem Used GB",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"below-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system_stats\")\n  |> filter(fn: (r) => r._field == \"Total\" or r._field == \"Available\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with used: float(v: r.Total) - float(v: r.Available) }))\n  |> map(fn: (r) => ({ r with used_GB: (float(v: r.Total) - float(v: r.Available)) }))\n  |> keep(columns: [\"_time\", \"used_GB\"])"
    }
   ]
  },
  {
   "title": "System Disks",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"below-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk_stats\")\n  |> filter(fn: (r) => r[\"Name\"] == \"sdb2\" or r[\"Name\"] == \"sdc2\" or r[\"Name\"] == \"sda1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Disk_Usage\")\n  |> map(fn: (r) => ({\n        r with Name: \n          if r.Name == \"sdb2\" then \"SDB 16TB\"\n          else if r.Name == \"sdc2\" then \"SDC 5TB\"\n          else if r.Name == \"sda1\" then \"SDA 4TB\"\n          else r.Name\n      }))\n  |> keep(columns: [\"_time\", \"_value\", \"Name\"])"
    }
   ]
  }
 ]
}